server:
  port: 9600

spring:
  application:
    name: springcloud-feign-client

eureka:
  client:
    serviceUrl:
      # 服务模块名称
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true